#pragma config(Motor,  port1,           drain1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           drain3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           drain4,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          drain2,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SLEW_STEP 2

#include "../Slew.c"

task main() {
	datalogClear();

	startTask(slew_task);

	while(true) {
		// Keep the program alive.

		datalogDataGroupStart();
		datalogAddValue( 0, nImmediateBatteryLevel);
		datalogDataGroupEnd();

		slew_set_motor(drain3, 100);
		slew_set_motor(drain4, 100);

		delay(25000);

		slew_set_motor(drain3, 0);
		slew_set_motor(drain4, 0);

		delay(5000);
	}
}
