#pragma config(Sensor, dgtl2,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           left1,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           right1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           right2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          left2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	Diego's General Programming Tips:

	You can check battery level by using nImmediateBatteryLevel; Found in Battery > Variables

	Controllers have accelerometers.

	Global variables are automaticalled extern'ed, so long as they aren't defined in main.c

	All sensor and motor ports are automatically extern'ed.
*/

#include "Setup.c"
#include "Controllers.c"
#include "Slew.c"
#include "PID.c"
#include "Serial.c"

task main() {
	while(true) {
		motor[left1] = vexRT[Ch2Xmtr2];

		// Keep the program alive.
		delay(TASK_DELAY);
	}
}
