#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	Diego's General Programming Tips:

	You can check battery level by using nImmediateBatteryLevel; Found in Battery > Variables

	Controllers have accelerometers.

	Global variables are automaticalled extern'ed, so long as they aren't defined in main.c

	All sensor and motor ports are automatically extern'ed.
*/

#include "Setup.h"
#include "Controllers.h"
#include "Slew.h"
#include "PID.h"
#include "Serial.h"

task main() {
	delay(1000);

	startTask(Slew);
	configurePort();

	//StartPIDTask();

	//LinkPID(leftMotor, leftEncoder);
	//LinkPID(rightMotor, rightEncoder, true);

	//SetPIDConstants(leftMotor, 1, 0, 0);
	//SetPIDConstants(rightMotor, 1, 0, 0);

	//SetPIDTarget(leftMotor, 1000);
	//SetPIDTarget(rightMotor, -1000);

	Packet controllerPacket;

	while(true) {
		updatePacket(controllerPacket);
		setSlewMotor(claw, controllerPacket.data[AXISX]);

		// Keep the program alive.
		delay(TASK_DELAY);
	}
}
