#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SLEW_STEP 1

#include "../Controllers.c"

task plotValues() {
	while(true) {
		datalogDataGroupStart();
		datalogAddValue(0, motor[left]);
		datalogAddValue(1, motor[right]);
		datalogDataGroupEnd();
		delay(TASK_DELAY);
	}
}


task main() {

	// No motors need to be attached! You can just view the datalog
	datalogClear();

	startTask(plotValues);
	startTask(slew_task);

	// All of these should have shallow, slow slopes.
	_controller_set_left(300); // This should be 127 on left
	_controller_set_right(300); // This should be 127 on right

	delay(3000);

	_controller_set_left(0);
	_controller_set_right(0);

	delay(3000);

	_controller_set_left(-127); // This should be -127 on left
	_controller_set_right(-127); // This should be -127 on right

	delay(3000);

	_controller_set_left(0);
	_controller_set_right(0);

	delay(3000);
}
