#pragma config(Sensor, dgtl2,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           left1,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           right1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           right2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          left2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	Make sure slew is working properly.
*/

#define SLEW_STEP 1 // Make step small enough to be noticable

#include "../Setup.c"
#include "../Slew.c"

void speedCheck(byte speed) {
	slew_set_motor(left1, speed);
	delay(3000);
	slew_set_motor(left1, 0);
	delay(5000);
}

task main() {

	startTask(slew_task);

	// You should see the motor ramping up to a slow pace in two directions.
	speedCheck(-60);
	speedCheck(60);

	// You should then see the motor ramping up to the maximum pace in two directions.
	speedCheck(-127);
	speedCheck(127);
}
